<div class='row'>
	<div class='col-md-3'>
	   <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">User</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
    	    <li><a href="/user/search" target="_blank">Search users</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Categories</h3>
          </div>
          <div class="panel-body admin-panel-body">
          	<ul>
    	    	<li><a href="/category/search" target="_blank">Search category</a></li>
    	    	<li><a href="/category/new" target="_blank">New category</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Products</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/product/search" target="_blank">Search product</a></li>
            	<li><a href="/product/new" target="_blank">New product</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Ad</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/ad/search" target="_blank">Search Ad</a></li>
            	<li><a href="/ad/new" target="_blank">New Ad</a></li>
    	    </ul>
          </div>
        </div>
	</div>
</div>

<div class='row'>
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Conf</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/conf/search" target="_blank">Search Conf</a></li>
            	<li><a href="/conf/new" target="_blank">New Conf</a></li>
    	    </ul>
          </div>
        </div>
	</div>
	
	<div class='col-md-3'>
	    <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Bill</h3>
          </div>
          <div class="panel-body admin-panel-body">
            <ul>
            	<li><a href="/bill/search" target="_blank">Search Bill</a></li>
            	<li><a href="/bill/new" target="_blank">New Bill</a></li>
            	<li><a href="/bill/search-carts" target="_blank">Manager Carts</a></li>
    	    </ul>
          </div>
        </div>
	</div>
</div>