<?php $lu = Zend_Registry::get('user');?>
<?php $categories = $this->categories;?>
<?php /***********************
	hp_product:: Sản phẩm được SEO đặt lên trang chủ
	recommend_product: Danh sách sản phẩm được Admin gợi ý cho người dùng
**/?>
<?php $hp_product = $this->hp_product;
	  $hp_product = Dao_Node_Product::getInstance()->getStandedProduct($hp_product);
?>
<?php $recommend_products = $this->recommend_products;?>
<div class="main module">
   <div class="row">
  <?php echo $this->render('widget/home-slider.phtml');?>
   <?php /**DANH SÁCH CHUYÊN MỤC VÀ 1 SẢN PHẨM ĐƯỢC GỢI Ý**/?>
   <?php 
   	   $this->product_list = $recommend_products;
  	   $this->product_list_name = "Sản phẩm được gợi ý";
  	   $this->product_list_link = "#";
  	   echo $this->render('widget/product_list.phtml');
    ?>
    
    <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CÁC CHUYÊN MỤC :: LOẠI 2**/?>
  <?php $categories_iids2 = $this->categories_iids2;?>
  <?php if(count($categories_iids2) > 0):?>
  <div id="channel-deals">
  	<?php foreach ($categories_iids2 as $cate):?>
  	<?php $products = isset($cate['products']) ? $cate['products'] : array();?>
	  	<?php if(count($products) > 0):?>
			<?php 
	  			$this->product_list = $products;
	  			$this->product_list_name = $cate['detail']['name'];
	  			$this->product_list_link = category_link($cate);;
	  			echo $this->render('widget/product_list.phtml');
	  		?>
	  	<?php endif;?>
	<?php endforeach;?>
  </div>
  <?php endif;?>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CHUYÊN MỤC :: STYLE 1**
  		Name_cofig:: products_iids1
  */?>  
  <?php 
  	$style1_products = $this->style1_products;
  	$this->product_list = $style1_products;
  	$this->product_list_name = "Dòng sản phẩm 1";
  	echo $this->render('widget/product_list.phtml');
  	?> 
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CÁC CHUYÊN MỤC :: LOẠI 1*
  		Name_cofig:: products_categories_iids1
  */?>
  
  <?php 
  	$categories_iids1 = $this->categories_iids1;
  ?>
  <?php if(count($categories_iids1) > 0):?>
  	 <div id="category-deals">
  	 <?php foreach ($categories_iids1 as $cate):?>
	  	<?php $products = isset($cate['products']) ? $cate['products'] : array();?>
	  	<?php if(count($products) > 0):?>
	  		<?php 
	  			$this->product_list = $products;
	  			$this->product_list_name = $cate['detail']['name'];
	  			$this->product_list_link = category_link($cate);
	  			echo $this->render('widget/product_list.phtml');
	  		?>
	  	<?php endif;?>
  	 <?php endforeach;?>
  	 </div>
  <?php endif;?>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CHUYÊN MỤC :: STYLE 2*
  		Name_cofig:: category_iid_style2
  */?>
  <?php 
  	$style2_products = $this->style2_products;
  	$this->product_list = $style2_products;
  	$this->product_list_name = "Dòng sản phẩm 2";
  	echo $this->render('widget/product_list.phtml'); 
  ?>
  
  <div style='min-height: 20px;'></div>
  <?php /**LẤY DANH SÁCH CHUYÊN MỤC PHỔ BIẾN**/?>
  
  <?php /**SLIDE BRAND**/?>
  <div class="container demo-1">
     <div class="main">
	<!-- Elastislide Carousel -->
		<ul id="carousel" class="elastislide-list">
			<li><a href="#" title='Apple'>
				<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/apple.jpg" alt="apple" />
					</a></li>
				<li><a href="#" title='Ariston'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/ariston.jpg" alt="ariston"/>
						</a></li>
				<li><a href="#" title='Asus'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/asus.jpg" alt="asus" />
						</a></li>
				<li><a href="#" title='Canon'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/canon.jpg" alt="canon" />
						</a></li>
				<li><a href="#" title='Dell'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/dell.jpg" alt="dell" />
						</a></li>
				<li><a href="#" title='Electrolux'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/electrolux.jpg" alt="electrolux" />
						</a></li>
				<li><a href="#" title='Hitachi'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/hitachi.jpg" alt="hitachi" />
						</a></li>
				<li><a href="#" title='Lenovo'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/lenovo.jpg" alt="lenovo" />
						</a></li title='LG'>
				<li><a href="#">
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/lg.jpg" alt="lg" />
						</a></li>
				<li><a href="#" title='Nokia'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/nokia.jpg" alt="nokia" />
						</a></li>
				<li><a href="#" title='Panasonic'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/panasonic.jpg" alt="panasonic" />
						</a></li>
				<li><a href="#" title='Samsung'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/samsung.jpg" alt="samsung" />
						</a></li>
				<li><a href="#" title='Sharp'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/sharp.jpg" alt="sharp" />
						</a></li>
				<li><a href="#" title='Sony'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/sony.jpg" alt="sony" />
						</a></li>
				<li><a href="#" title='Toshiba'>
					<img src="<?php echo ASSETS_CDN;?>/Elastislide/images/brand/toshiba.jpg" alt="toshiba" />
						</a></li>
		</ul>
	</div>
  </div>
</div>
</div>
