<?php $lu = Zend_Registry::get('user');?>
<?php $categories = $this->categories;?>
<?php /***********************
	hp_product:: Sản phẩm được SEO đặt lên trang chủ
	recommend_product: Danh sách sản phẩm được Admin gợi ý cho người dùng
**/?>
<?php $hp_product = $this->hp_product;
	  $hp_product = Dao_Node_Product::getInstance()->getStandedProduct($hp_product);
?>
<?php $recommend_products = $this->recommend_products;?>
<div class="main module">
	
   <?php /**DANH SÁCH CHUYÊN MỤC VÀ 1 SẢN PHẨM ĐƯỢC GỢI Ý**/?>
   <div class="row">
    <div class="three columns">
      <div data-bhw-path="LeftNavCategories" id="left-nav-categories" data-bhw="LeftNavCategories">
        <div class="side-title">
          <img src="http://gtgiaodien.local/homepage-assets/left_nav-viewing_glass-3956c58010.png" class="explore-icon">
          <h2>Chuyên mục</h2>
        </div>
        <ul>
          <?php if(isset($categories)):?>
          	<?php foreach ($categories as $ca):?>
		      <li><a href=""><?php echo $ca['name']?>
		      <?php $count_child = (isset($ca['child_category']) && count($ca['child_category']) > 0) ? count($ca['child_category']) : 0;?>
		      		<span class="counter">(<?php echo $count_child;?>)</span></a></li>
          	<?php endforeach;?>
          <?php endif;?>
	  </ul>
      </div>   
    </div>
    <div class="nine columns">
      <div id="featured">
        <figure class="hero-deal">
		  <a href="" title='<?php echo $hp_product['name'];?>'>
		    <img src="https://img.grouponcdn.com/deal/ano8GcENUPt3hgXU431e/DB-2048x1229/v1/c698x422.jpg">
		  </a>
		  <figcaption>
		    <h2>
		      <a href="" title='<?php echo $hp_product['name'];?>'><?php echo $hp_product['name'];?></a>
		    </h2>
		
		    <div class="deal-metadata">
		        <p style="word-wrap: break-word;" 
		        	class="merchant-name should-truncate">
		        	<?php echo $hp_product['category']?></p>
		        <p class="meta-divider">|</p>
		        <p style="word-wrap: break-word;" class="deal-location should-truncate">
		        	<?php echo $hp_product['counter']['buy'];?> đã mua</p>
		    </div>
		
		    <p class="deal-price">
		        <s class="original-price" title='Giá ban đầu'>$<?php echo $hp_product['price'];?></s>
		      $<?php echo $hp_product['saled'];?>
		    </p>
		    <div class="view-deal">
		      <a href="" class="btn-buy" data-bhw="ViewDealButton">Xem chi tiết</a>
		    </div>
		  </figcaption>
		</figure>

      </div>
    </div>
  </div>
  
  
  <?php /**DANH SÁCH SẢN PHẨM ĐƯỢC ADMIN GỢI Ý**/?>
  <div id="featured-deals">
    <section class="deal-pack row pad-row">
	  <div class="section-head">
	      <a href="/browse">
	      <h2>Sản phẩm có thể bạn thích</h2></a>
	      <a class="view-all" href="/browse">Xem tất cả</a>
	  </div>
	  <div class="block-grid four-up">
	  	  <?php if(count($recommend_products) > 0):?>
	  	  	<?php foreach ($recommend_products as $product):?>
	  	  	  <?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
		      <figure class="deal-card">
		        <a href="">
		          <img src="https://img.grouponcdn.com/deal/mzY57gUUDKc3v1yo9EVe/xC-2048x1242/v1/c220x134.jpg">
		          <figcaption>
		            <p style="word-wrap: break-word;" 
		            	class="deal-title should-truncate"><?php echo $product['name'];?></p>
		            <p style="word-wrap: break-word;" 
		            	class="merchant-name should-truncate"><?php echo $product['category']['name'];?></p>
			        <p style="word-wrap: break-word;" 
			        	class="deal-location should-truncate"><?php echo $product['count']['buy'];?> đã mua</p>
			        	
		  	        <p class="deal-price">
						<s class="original-price">$<?php echo $product['price'];?></s>
						$<?php echo $product['saled'];?>
		            </p>
		          </figcaption>
		        </a>
		      </figure>
	  	  	<?php endforeach;?>
	  	  <?php endif;?>
	  </div>
	</section>
  </div>
  
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CHUYÊN MỤC :: STYLE 1**
  		Name_cofig:: products_iids1
  */?>  
  <?php $style1_products = $this->style1_products;?>
  <div id="national-occasion" style='border: medium none;'>
    <section class="row theme-image-three-up">
	  <div class="theme-image-caption">
	    <h2 class="theme-image-caption-header"></h2>
	    <p class="theme-image-caption-subheader"></p>
	  </div>
	  
	  <?php $first = $style1_products[0];?>
	  <a class="six columns theme-image" href="">
	    <img src="https://img.grouponcdn.com/deal/m2hkvgB2oTkmwaJnzJPXRo/hbw-spring_break-460x315">
	  </a>
	  
	  <div class="six columns deals">
	  	  <?php if(count($style1_products) > 0):?>
	  	  	<?php $i = 0;?>
	  	  	<?php foreach ($style1_products as $product):?>
	  	  		<?php if($i > 0):?>
	  	  			<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
	  	  			 <figure class="deal-card-mini">
				        <a href="">
				          <img src="https://img.grouponcdn.com/deal/pgb9941LrE1Eswgib6fC/Cq-2048x1229/v1/c125x75.jpg">
				        </a>
				        <figcaption>
				          <a href="">
				            <p style="word-wrap: break-word;" class="deal-title should-truncate">
				            	<?php echo $product['name'];?></p>
				          </a>
				          <p class="deal-price">
				            <s class="original-price">$<?php echo $product['price'];?></s>
				            	 $<?php echo $product['saled'];?>
				          </p>
				            <p style="word-wrap: break-word;" class="deal-location should-truncate">
				            <?php echo $product['category']['name'];?></p>
				  		</figcaption>
				      </figure>
	  	  		<?php endif;?>
	  	  		<?php $i ++;?>
	  	  	<?php endforeach;?>
	  	  <?php endif;?>
	      <a class="view-all"
	      	 href="/occasion/spring-break-beauty-deals">Xem tất cả</a>
	  </div>
	</section>

  </div>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CÁC CHUYÊN MỤC :: LOẠI 1*
  		Name_cofig:: products_categories_iids1
  */?>
  
  <?php $categories_iids1 = $this->categories_iids1;?>
  <?php if(count($categories_iids1) > 0):?>
  	 <div id="category-deals">
  	 <?php foreach ($categories_iids1 as $cate):?>
  	 	<section class="deal-pack row pad-row">
		  <div class="section-head">
		      <a href=""><h2><?php echo $cate['detail']['name'];?></h2></a>
		      <a class="view-all" href="">Xem tất cả</a>
		  </div>
		  
		  <div class="block-grid four-up">
		  	<?php $products = isset($cate['products']) ? $cate['products'] : array();?>
		  	<?php if(count($products) > 0):?>
		  		<?php foreach ($products as $product):?>
		  		<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
			      <figure class="deal-card">
			        <a href="">
			          <img src="https://img.grouponcdn.com/deal/gMgyKW1cFX5e4MRj9Fj5/aD-2048x1229/v1/c220x134.jpg">
			          <figcaption>
			            <p style="word-wrap: break-word;" class="deal-title should-truncate">
			            	<?php echo $product['name'];?></p>
			            <p style="word-wrap: break-word;" class="merchant-name should-truncate">
			            	<?php echo $product['category']['name'];?></p>
					    <p style="word-wrap: break-word;" class="deal-location should-truncate">
					    	<?php echo $product['counter']['buy'];?> đã mua</p>
				        <p class="deal-price">
			                <s class="original-price">$<?php echo $product['price'];?></s>
					        $<?php echo $product['saled'];?>
			            </p>
			          </figcaption>
			        </a>
			      </figure>
		  		<?php endforeach;?>
		  	<?php endif;?>
		  </div>
		</section>
  	 <?php endforeach;?>
  	 </div>
  <?php endif;?>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CHUYÊN MỤC :: STYLE 2*
  		Name_cofig:: category_iid_style2
  */?>
  <?php $style2_products = $this->style2_products;?>
  <div id="manual-merchandising" style='border: medium none;'>
    <section class="row theme-image-three-up">
	  <div class="theme-image-caption">
	    <h2 class="theme-image-caption-header"></h2>
	    <p class="theme-image-caption-subheader"></p>
	  </div>
	   <?php $first = $style2_products[0];?>
	  <a class="six columns theme-image" href="">
	    <img src="https://img.grouponcdn.com/deal/f5agcyXmxw8dK3L5C7K4x6/top_destinations-getaways-460x315">
	  </a>
	  <div class="six columns deals">
	     <?php if(count($style2_products) > 0):?>
	  	  	<?php $i = 0;?>
	  	  	<?php foreach ($style2_products as $product):?>
	  	  		<?php if($i > 0):?>
	  	  			<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
	  	  			 <figure class="deal-card-mini">
				        <a href="">
				          <img src="https://img.grouponcdn.com/deal/pgb9941LrE1Eswgib6fC/Cq-2048x1229/v1/c125x75.jpg">
				        </a>
				        <figcaption>
				          <a href="">
				            <p style="word-wrap: break-word;" class="deal-title should-truncate">
				            	<?php echo $product['name'];?></p>
				          </a>
				          <p class="deal-price">
				            <s class="original-price">$<?php echo $product['price'];?></s>
				            	 $<?php echo $product['saled'];?>
				          </p>
				            <p style="word-wrap: break-word;" class="deal-location should-truncate">
				            <?php echo $product['category']['name'];?></p>
				  		</figcaption>
				      </figure>
	  	  		<?php endif;?>
	  	  		<?php $i ++;?>
	  	  	<?php endforeach;?>
	  	  <?php endif;?>
	      <a class="view-all"
	      	 href="/occasion/spring-break-beauty-deals">Xem tất cả</a>
      </div>
    </section>
	
  </div>
  <?php /**LẤY DANH SÁCH CHUYÊN MỤC PHỔ BIẾN**/?>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CÁC CHUYÊN MỤC :: LOẠI 2**/?>
  <?php $categories_iids2 = $this->categories_iids2;?>
  <?php if(count($categories_iids2) > 0):?>
  <div id="channel-deals">
  	<?php foreach ($categories_iids2 as $cate):?>
	  <section class="deal-pack row pad-row">
		  <div class="section-head">
		      <a dhref="/getaways"><h2><?php echo $cate['detail']['name'];?></h2></a>
		      <a class="view-all" href="" >Xem tất cả</a>
		  </div>
		  <div class="block-grid three-up">
		  	<?php $products = isset($cate['products']) ? $cate['products'] : array();?>
			  	<?php if(count($products) > 0):?>
			  		<?php foreach ($products as $product):?>
			  		<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
			      <figure class="deal-card">
			        <a href="">
			          <img src="https://img.grouponcdn.com/deal/wabicVhyZth8ieDDBo3b/wr-960x582/v1/c300x181.jpg">
			          <figcaption>
			            <p style="word-wrap: break-word;" class="deal-title should-truncate">
			            	<?php echo $product['name'];?></p>
			            <p style="word-wrap: break-word;" class="merchant-name should-truncate">
			       		     <?php echo $product['category']['name'];?></p>
			            <p style="word-wrap: break-word;" class="deal-location should-truncate">
			          		 <?php echo $product['counter']['buy'];?> đã mua</p>
			            <p class="deal-price">
			                <s class="original-price">$<?php echo $product['price'];?></s>
			        	   $<?php echo $product['saled'];?>
			            </p>
			          </figcaption>
			        </a>
			      </figure>
		      <?php endforeach;?>
		  	<?php endif;?>
		  </div>
		</section>
	<?php endforeach;?>
  </div>
</div>
<?php endif;?>
