<?php $lu = Zend_Registry::get('user');?>
<?php $categories = $this->categories;?>
<?php /***********************
	hp_product:: Sản phẩm được SEO đặt lên trang chủ
	recommend_product: Danh sách sản phẩm được Admin gợi ý cho người dùng
**/?>
<?php $hp_product = $this->hp_product;
	  $hp_product = Dao_Node_Product::getInstance()->getStandedProduct($hp_product);
?>
<?php $recommend_products = $this->recommend_products;?>
<div class="main module">
	
   <?php /**DANH SÁCH CHUYÊN MỤC VÀ 1 SẢN PHẨM ĐƯỢC GỢI Ý**/?>
   <div class="row">
    <div class="three columns">
      <div data-bhw-path="LeftNavCategories" id="left-nav-categories" data-bhw="LeftNavCategories">
        <div class="side-title">
          <img src="<?php echo ASSETS_CDN?>/homepage-assets/left_nav-viewing_glass-3956c58010.png" class="explore-icon">
          <h2>Chuyên mục</h2>
        </div>
        <ul>
          <?php if(isset($categories)):?>
          	<?php foreach ($categories as $ca):?>
		      <li>
		      	<a href="<?php echo category_link($ca)?>">
		      		<?php echo $ca['name']?>
		      <?php $count_child = (isset($ca['child_category']) && count($ca['child_category']) > 0) ? count($ca['child_category']) : 0;?>
		      		<span class="counter">(<?php echo $count_child;?>)</span></a></li>
          	<?php endforeach;?>
          <?php endif;?>
	  </ul>
      </div>   
    </div>
    <div class="nine columns">
      <div id="featured">
        <figure class="hero-deal">
		  <a href="<?php echo node_link('product', $hp_product);?>" title='<?php echo $hp_product['name'];?>'>
              <img src="<?php
                   echo STATIC_GT . $hp_product['images'];
                   $url = STATIC_GT . $hp_product['images'];
                   ?>"
                   <?php  /*Giup hien thi phan giua cua anh*/
                   /*(Filled image widget new|hot|vote)*/
	               list($width, $height) = getimagesize($url);
	               $heightFilledImage = 422;//height class filedImage img
					$widthFilledImage = 702;
	                
	                //Get height (chieu dai thuc cua anh ty le
	                // voi chieu dai cua khung chua anh)
	                $heightFilledImageNew = $widthFilledImage * $height/ $width;
	                
	                $gap = ($heightFilledImageNew - $heightFilledImage)/2;
	                if($gap > 0){
	                	echo "style = 'margin-top: -{$gap}px'";
	                }
	                ?>
                    width='100%'>
		  </a>
		  <figcaption>
		    <h2>
		      <a href="<?php echo node_link('product', $hp_product);?>" 
		      	title='<?php echo $hp_product['name'];?>'><?php echo $hp_product['name'];?></a>
		    </h2>
		
		    <div class="deal-metadata">
		    <?php /*
		        <p style="word-wrap: break-word;" 
		        	class="merchant-name should-truncate">
		        	<?php echo $hp_product['category']?></p>
		        <p class="meta-divider">|</p>
		    */?>
		        <p style="word-wrap: break-word;" class="deal-location should-truncate">
		        	<?php echo $hp_product['counter']['buy'];?> đã mua</p>
		    </div>
		
		    <p class="deal-price">
		        <s class="original-price" title='Giá ban đầu'><?php echo $hp_product['origin_price'];?>₫</s>
		      <?php echo $hp_product['deal_price'];?>₫
		    </p>
		    <div class="view-deal">
		      <a href="<?php echo node_link('product', $hp_product);?>" class="btn-buy">Xem chi tiết</a>
		    </div>
		  </figcaption>
		</figure>

      </div>
    </div>
  </div>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CHUYÊN MỤC :: STYLE 1**
  		Name_cofig:: products_iids1
  */?>  
  <?php $style1_products = $this->style1_products;?>
  <div id="national-occasion" style='border: medium none;'>
    <section class="row theme-image-three-up" style='overflow: hidden'>
	  <div class="theme-image-caption">
	    <h2 class="theme-image-caption-header"></h2>
	    <p class="theme-image-caption-subheader"></p>
	  </div>
	  
	  <?php $first = $style1_products[0];?>
	  <a class="six columns theme-image" href="<?php echo node_link('product', $first);?>">
	    <img src="<?php
                   echo STATIC_GT . $first['images'];
                   $url = STATIC_GT . $first['images'];
                   ?>"
                   <?php  /*Giup hien thi phan giua cua anh*/
                   /*(Filled image widget new|hot|vote)*/
	               list($width, $height) = getimagesize($url);
	               $heightFilledImage = 317;//height class filedImage img
					$widthFilledImage = 462;
	                
	                //Get height (chieu dai thuc cua anh ty le
	                // voi chieu dai cua khung chua anh)
	                $heightFilledImageNew = $widthFilledImage * $height/ $width;
	                
	                $gap = ($heightFilledImageNew - $heightFilledImage)/2;
	                if($gap > 0){
	                	echo "style = 'margin-top: -{$gap}px'";
	                }
	                ?>
                    width='100%'>
	  </a>
	  
	  <div class="six columns deals">
	  	  <?php if(count($style1_products) > 0):?>
	  	  	<?php $i = 0;?>
	  	  	<?php foreach ($style1_products as $product):?>
	  	  		<?php if($i > 0):?>
	  	  			<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
	  	  			 <figure class="deal-card-mini">
				        <a href="<?php echo node_link('product', $product);?>">
				          <img src="<?php echo STATIC_GT . $product['images'];?>" style='max-height: 60px;'>
				        </a>
				        <figcaption>
				          <a href="<?php echo node_link('product', $product);?>">
				            <p style="word-wrap: break-word;" class="deal-title should-truncate">
				            	<?php echo $product['name'];?></p>
				          </a>
				          <p class="deal-price">
				            <s class="original-price"><?php echo show_money($product['origin_price']);?>₫</s>
				            	 <?php echo show_money($product['deal_price']);?>₫
				          </p>
				            <p style="word-wrap: break-word;" class="deal-location should-truncate">
				            <?php echo $product['category']['name'];?></p>
				  		</figcaption>
				      </figure>
	  	  		<?php endif;?>
	  	  		<?php $i ++;?>
	  	  	<?php endforeach;?>
	  	  <?php endif;?>
	      <a class="view-all"
	      	 href="#">Xem tất cả</a>
	  </div>
	</section>

  </div>
  
  <?php /**DANH SÁCH SẢN PHẨM ĐƯỢC ADMIN GỢI Ý**/?>
  <?php /*
  <div id="featured-deals">
    <section class="deal-pack row pad-row">
	  <div class="section-head">
	      <a href="#">
	      <h2>Sản phẩm có thể bạn thích</h2></a>
	      <a class="view-all" href="#">Xem tất cả</a>
	  </div>
	  <div class="block-grid four-up">
	  	  <?php if(count($recommend_products) > 0):?>
	  	  	<?php foreach ($recommend_products as $product):?>
	  	  	  <?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
		      <figure class="deal-card">
		        <a href="<?php echo node_link('product', $product);?>">
		          <img src="<?php echo STATIC_GT.$product['images'];?>">
		          <figcaption>
		            <p style="word-wrap: break-word;" 
		            	class="deal-title should-truncate"><?php echo $product['name'];?></p>
		            <p style="word-wrap: break-word;" 
		            	class="merchant-name should-truncate"><?php echo $product['category']['name'];?></p>
			        <p style="word-wrap: break-word;" 
			        	class="deal-location should-truncate"><?php echo $product['counter']['buy'];?> đã mua</p>
			        	
		  	        <p class="deal-price">
						<s class="original-price"><?php echo show_money($product['origin_price']);?>₫</s>
						<?php echo show_money($product['deal_price']);?>₫
		            </p>
		          </figcaption>
		        </a>
		      </figure>
	  	  	<?php endforeach;?>
	  	  <?php endif;?>
	  </div>
	</section>
  </div>
  */?>
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CÁC CHUYÊN MỤC :: LOẠI 1*
  		Name_cofig:: products_categories_iids1
  */?>
  
  <?php $categories_iids1 = $this->categories_iids1;?>
  <?php if(count($categories_iids1) > 0):?>
  	 <div id="category-deals">
  	 <?php foreach ($categories_iids1 as $cate):?>
	  	<?php $products = isset($cate['products']) ? $cate['products'] : array();?>
	  	<?php if(count($products) > 0):?>
	  	 	<section class="deal-pack row pad-row">
			  <div class="section-head">
			      <a href="<?php echo category_link($cate['detail'])?>"><h2>
			      	<?php echo $cate['detail']['name'];?></h2></a>
			  </div>
		  
		     <div class="block-grid four-up">
		  		<?php foreach ($products as $product):?>
		  		<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
			      <figure class="deal-card">
			        <a href="<?php echo node_link('product', $product);?>">
			          <img src="<?php echo STATIC_GT . $product['images'];?>">
			          <figcaption>
			            <p style="word-wrap: break-word;" class="deal-title should-truncate">
			            	<?php echo $product['name'];?></p>
			            <p style="word-wrap: break-word;" class="merchant-name should-truncate">
			            	<?php echo $product['category']['name'];?></p>
					    <p style="word-wrap: break-word;" class="deal-location should-truncate">
					    	<?php echo $product['counter']['buy'];?> đã mua</p>
				        <p class="deal-price">
			                <s class="original-price"><?php echo show_money($product['origin_price']);?>₫</s>
					        <?php echo show_money($product['deal_price']);?>₫
			            </p>
			          </figcaption>
			        </a>
			      </figure>
		  		<?php endforeach;?>
				  </div>
			</section>
	  	<?php endif;?>
  	 <?php endforeach;?>
  	 </div>
  <?php endif;?>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CHUYÊN MỤC :: STYLE 2*
  		Name_cofig:: category_iid_style2
  */?>
  <?php $style2_products = $this->style2_products;?>
  <div id="manual-merchandising" style='border: medium none;'>
    <section class="row theme-image-three-up" style='overflow: hidden'>
	  <div class="theme-image-caption">
	    <h2 class="theme-image-caption-header"></h2>
	    <p class="theme-image-caption-subheader"></p>
	  </div>
	   <?php $first = $style2_products[0];?>
	  <a class="six columns theme-image" href="<?php echo node_link('product', $first);?>">
	    <img src="<?php
                   echo STATIC_GT . $first['images'];
                   $url = STATIC_GT . $first['images'];
                   ?>"
                   <?php  /*Giup hien thi phan giua cua anh*/
                   /*(Filled image widget new|hot|vote)*/
	               list($width, $height) = getimagesize($url);
	               $heightFilledImage = 317;//height class filedImage img
					$widthFilledImage = 462;
	                
	                //Get height (chieu dai thuc cua anh ty le
	                // voi chieu dai cua khung chua anh)
	                $heightFilledImageNew = $widthFilledImage * $height/ $width;
	                
	                $gap = ($heightFilledImageNew - $heightFilledImage)/2;
	                if($gap > 0){
	                	echo "style = 'margin-top: -{$gap}px'";
	                }
	                ?>
                    width='100%'>
	    
	  </a>
	  <div class="six columns deals">
	     <?php if(count($style2_products) > 0):?>
	  	  	<?php $i = 0;?>
	  	  	<?php foreach ($style2_products as $product):?>
	  	  		<?php if($i > 0):?>
	  	  			<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
	  	  			 <figure class="deal-card-mini">
				        <a href="<?php echo node_link('product', $product);?>">
				          <img src="<?php echo STATIC_GT . $product['images'];?>"  style='max-height: 60px;'>
				        </a>
				        <figcaption>
				          <a href="<?php echo node_link('product', $product);?>">
				            <p style="word-wrap: break-word;" class="deal-title should-truncate">
				            	<?php echo $product['name'];?></p>
				          </a>
				          <p class="deal-price">
				            <s class="original-price"><?php echo show_money($product['origin_price']);?>₫</s>
				            	 <?php echo $product['deal_price'];?>₫
				          </p>
				            <p style="word-wrap: break-word;" class="deal-location should-truncate">
				            <?php echo $product['category']['name'];?></p>
				  		</figcaption>
				      </figure>
	  	  		<?php endif;?>
	  	  		<?php $i ++;?>
	  	  	<?php endforeach;?>
	  	  <?php endif;?>
	      <a class="view-all"
	      	 href="#">Xem tất cả</a>
      </div>
    </section>
	
  </div>
  <?php /**LẤY DANH SÁCH CHUYÊN MỤC PHỔ BIẾN**/?>
  
  <?php /**LẤY DANH SÁCH SẢN PHẨM THEO IID ĐƯỢC CONFIG CỦA DANH SÁCH CÁC CHUYÊN MỤC :: LOẠI 2**/?>
  <?php $categories_iids2 = $this->categories_iids2;?>
  <?php if(count($categories_iids2) > 0):?>
  <div id="channel-deals">
  	<?php foreach ($categories_iids2 as $cate):?>
  	<?php $products = isset($cate['products']) ? $cate['products'] : array();?>
	  	<?php if(count($products) > 0):?>
		  <section class="deal-pack row pad-row">
			  <div class="section-head">
			      <a href="<?php echo category_link($cate['detail'])?>">
			      	<h2><?php echo $cate['detail']['name'];?></h2></a>
			  </div>
			  <div class="block-grid three-up">
			  	<?php foreach ($products as $product):?>
			  		<?php $product = Dao_Node_Product::getInstance()->getStandedProduct($product);?>
			      <figure class="deal-card">
			        <a href="<?php echo node_link('product', $product);?>">
			          <img src="<?php
		                   echo STATIC_GT . $product['images'];
		                   $url = STATIC_GT . $product['images'];
		                   ?>"
		                   <?php  /*Giup hien thi phan giua cua anh*/
		                   /*(Filled image widget new|hot|vote)*/
			               list($width, $height) = getimagesize($url);
			               $heightFilledImage = 134;//height class filedImage img
							$widthFilledImage = 222;
			                
			                //Get height (chieu dai thuc cua anh ty le
			                // voi chieu dai cua khung chua anh)
			                $heightFilledImageNew = $widthFilledImage * $height/ $width;
			                
			                $gap = ($heightFilledImageNew - $heightFilledImage)/2;
			                if($gap > 0){
			                	echo "style = 'margin-top: -{$gap}px'";
			                }
			                ?>
		                    width='100%'>
			          <figcaption>
			            <p style="word-wrap: break-word;" class="deal-title should-truncate">
			            	<?php echo $product['name'];?></p>
			            <p style="word-wrap: break-word;" class="merchant-name should-truncate">
			       		     <?php echo $product['category']['name'];?></p>
			            <p style="word-wrap: break-word;" class="deal-location should-truncate">
			          		 <?php echo $product['counter']['buy'];?> đã mua</p>
			            <p class="deal-price">
			                <s class="original-price"><?php echo show_money($product['origin_price']);?>₫</s>
			        	   <?php echo show_money($product['deal_price']);?>₫
			            </p>
			          </figcaption>
			        </a>
			      </figure>
			      <?php endforeach;?>
			  </div>
			</section>
	  	<?php endif;?>
	<?php endforeach;?>
  </div>
	<?php endif;?>
</div>
