<?php $page = Zend_Registry::get('page');?>
<ul class='nav nav-pills'>
	<li <?php if ($page == 'category/index/new') echo "class='active';"?>><a href="/category/new">New</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'category/index/update') echo "class='active';"?>><a href="/category/update<?php if (isset($this->row['id'])) echo "?id=" . $this->row['id'];?>"">Update</a></li>
	<?php endif;?>    
	<li <?php if ($page == 'category/index/search') echo "class='active';"?>><a href="/category/search">Search</a></li>
	<? if (isset($this->row)) :?>    
	<li <?php if ($page == 'category/index/view') echo "class='active';"?>><a href="/category/<?php if (isset($this->row['id'])) echo "" . $this->row['id'];?>">View</a></li>
	<?php endif;?>
</ul>
<div class='separator'></div>
