<div class='row'>
    <div class='col-md-12'>
        <div class="row well">
        	<br />
        	<?php if($this->total > 0) :?>
                <?php echo $this->render("widget/pagination.phtml");?>
            <?php endif;?>
        	<form action="/product/search" method="GET" class='' id="search_form" style="display: inline;">
            <div class="col-md-4">
                <?php echo $this->form->supplierName;?>
                <?php echo $this->form->model;?>
                <?php echo $this->form->stockStatus;?>
                
            </div>
            <div class="col-md-4">
                <?php echo $this->form->iid;?>
                <?php echo $this->form->name;?>
                <?php echo $this->form->serialNumber;?>
            </div>
            <div class="col-md-4">
                <?php echo $this->form->price;?>
				<?php echo $this->form->_cl_submit; ?>
				<?php echo $this->form->page //auto add to search - use for splitview?>
            </div>
            </form>
        </div>
        <div class="separator"></div>
         <h4>Danh sách sản phẩm</h4>
        
        <div class="clear"></div>
        <br>
         <?php if($this->count > 0) :?>
        <div class="row well">
    	<table class="table table-striped table-bordered table-condensed zebra-striped tablesorter" id='search-result-details'>
    		<thead id='head-table'>
    				<tr>
                        <th><b><input type="checkbox" class="checkall" /></b></th>
                        <th><b>iid</b></th>
                        <th><b>Người tạo</b></th>
                        <th><b>Tên</b></th>
                        <th><b>Model</b></th>
                        <th><b>SerialNumber</b></th>
                        <th><b>Ngày nhận</b></th>
                        <th><b>StockStatus</b></th>
                        <th><b>Chú ý</b></th>
                        <th><b>Mô t</b></th>
                        <th><b>Giá</b></th>
                        <th><b>Trạng thái</b></th>
                        <th><b>Actions</b></th>
                    </tr>
    		</thead>
    				<tbody>
    			<?php foreach($this->list as $row) :?>
    			<tr id="<?php echo $row['id'];?>" >
    			<?php /*<td><a href="<?php echo node_link('product', $row);?>"><?php echo $row['Model'];?></a></td>*/?>
    				<td> <input type="checkbox" value="<?php echo $row['_id'];?>" class="check-item" 
    				data-sn='<?php echo $row['serialNumber'];?>'
    				/> </td>
    				<td><?php echo $row['iid'];?></td>
    				<td><?php echo $row['supplierName'];?></td>
    				<td>
    					<a href="<?php echo node_link('product', $row);?>">
    						<?php echo $row['name'];?></a></td>
    				<td><?php echo $row['model'];?></td>
    				<td><?php echo $row['serialNumber'];?></td>
    				<td><?php echo $row['receivedDate'];?></td>
    				<td><?php 
    					$row['stockStatus'] = isset($row['stockStatus']) ? $row['stockStatus'] : 0;
    					echo $row['stockStatus'];?></td>
    				<td><?php echo $row['note'];?></td>
    				<td><?php echo $row['description'];?></td>
    				<td><?php echo $row['price'];?></td>				
    	            <td>
                        <div class="btn-group">
        			    	<a href="/product/update?id=<?php echo $row['id'];?>&status=queued&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='queued') echo 'active';?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group"> Đang ch </a>
        			    	<a href="/product/update?id=<?php echo $row['id'];?>&status=approved&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='approved') echo 'active';?> cl_ajax"
        			    	 _cl_get_metadata="active_button_group"> Đã duyệt</a>
        			    </div> 
        			</td>
    				<td>
    				    <a href="/product/update?id=<?php echo $row['id'];?>" class="btn btn-xs btn-default">
    				    	<i class="icon-edit"></i>Sửa</a>
    				    <a href="/related/search?product__id=<?php echo $row['id'];?>" class="btn btn-xs btn-default">
    				    	<i class="icon-edit"></i>So sánh</a>
    				    <?php if (has_perm('admin_product')):?>
    				    <a href="/product/delete?id=<?php echo $row['id'];?>" class="btn btn-xs btn-danger cl_ajax" 
    				        _cl_get_metadata="remove_my_parent:2"
    				        _cl_ajax_confirm='Are you sure you want to permanently delete this item?'
    				        >
                           <i class="icon-remove"></i>Xóa
    				       </a>
    				    <?php endif;?>
    			   </td>
    			</tr>
    			<?php endforeach; ?>	
    		</tbody>
            		
    	</table>
    	</div>
    	<?php else:?>
        	<h3 style="text-align: center; color: red;">No item found</h3>
        <?php endif;?>
    </div>
</div>