<div class='row'>
    <div class='col-md-12'>
        <div class="row well">
        	<br />
        	<?php if($this->total > 0) :?>
                <?php echo $this->render("widget/pagination.phtml");?>
            <?php endif;?>
        	<form action="/product/search" method="GET" class=''>
        	<?php 
        	      $this->form->setDisplayInline ();
        	      $this->form->setAttrib ( 'id', 'search_form' );
            ?>
            <div class="col-md-4">
                <?php echo $this->form->supplierName;?>
                <?php echo $this->form->model;?>
            </div>
            <div class="col-md-4">
                <?php echo $this->form->name;?>
                <?php echo $this->form->serialNumber;?>
            </div>
            <div class="col-md-4">
                <?php echo $this->form->price;?>
				<?php echo $this->form->_cl_submit; ?>
				<?php echo $this->form->page //auto add to search - use for splitview?>
            </div>
            </form>
        </div>
        <div class="separator"></div>
         <h4>Product item list</h4>
        
        <div class="clear"></div>
        <br>
         <?php if($this->count > 0) :?>
    	<table class="table table-striped table-bordered table-condensed zebra-striped tablesorter" id='search-result-details'>
    		<thead id='head-table'>
    				<tr>
                        <th><b><input type="checkbox" class="checkall" /></b></th>
                        <th><b>SupplierName</b></th>
                        <th><b>Name</b></th>
                        <th><b>Model</b></th>
                        <th><b>SerialNumber</b></th>
                        <th><b>ReceivedDate</b></th>
                        <th><b>StockStatus</b></th>
                        <th><b>Note</b></th>
                        <th><b>Description</b></th>
                        <th><b>Price</b></th>
                        <th><b>Set Status</b></th>
                        <th><b>Actions</b></th>
                    </tr>
    		</thead>
    				<tbody>
    			<?php foreach($this->list as $row) :?>
    			<tr id="<?php echo $row['id'];?>" >
    			<?php /*<td><a href="<?php echo node_link('product', $row);?>"><?php echo $row['Model'];?></a></td>*/?>
    				<td> <input type="checkbox" value="<?php echo $row['_id'];?>" class="check-item" 
    				data-sn='<?php echo $row['serialNumber'];?>'
    				/> </td>
    				<td><?php echo $row['supplierName'];?></a></td>
    				<td><?php echo $row['name'];?></td>
    				<td><?php echo $row['model'];?></td>
    				<td><?php echo $row['serialNumber'];?></td>
    				<td><?php echo $row['receivedDate'];?></td>
    				<td><?php echo $row['stockStatus'];?></td>
    				<td><?php echo $row['note'];?></td>
    				<td><?php echo $row['description'];?></td>
    				<td><?php echo $row['price'];?></td>				
    	            <td>
                        <div class="btn-group">
        			    	<a href="/product/update?id=<?php echo $row['id'];?>&status=queued&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='queued') echo 'active';?> cl_ajax" 
        			    	_cl_get_metadata="active_button_group"> Queued </a>
        			    	<a href="/product/update?id=<?php echo $row['id'];?>&status=approved&_cl_step=status"
        			    	class="btn btn-primary btn-xs <?php if($row['status']=='approved') echo 'active';?> cl_ajax" _cl_get_metadata="active_button_group"> Approved</a>
        			    </div> 
        			</td>
    				<td>
    				    <a href="/product/update?id=<?php echo $row['id'];?>" class="btn btn-mini"><i class="icon-edit"></i>Edit</a>
    				    <?php if (has_perm('admin_product')):?>
    				    <a href="/product/delete?id=<?php echo $row['id'];?>" class="btn btn-mini btn-danger cl_ajax" 
    				        _cl_get_metadata="remove_my_parent:2"
    				        _cl_ajax_confirm='Are you sure you want to permanently delete this item?'
    				        >
                           <i class="icon-remove"></i>Delete
    				       </a>
    				    <?php endif;?>
    			   </td>
    			</tr>
    			<?php endforeach; ?>	
    		</tbody>
            		
    	</table>
    	
    	<?php else:?>
        	<h3 style="text-align: center; color: red;">No item found</h3>
        <?php endif;?>
    </div>
</div>