<div class='row'>
    <div class='span12'>
    	<br />
    	<?php if($this->total > 0) :?>
            <?php echo $this->render("widget/pagination.phtml");?>
        <?php endif;?>
            <?php //echo $this->render('widget/table.phtml');?>
            <?php
            /* 
        <a href="/<?php echo $this->module?>/bulk-delete" class="cl_ajax btn btn-mini">Bulk Delete</a>
        */
            ?>
         <h4>Product item list</h4>
        
        <div class="clear"></div>
        <br>
         <?php if($this->count > 0) :?>
    	<table class="table table-striped table-bordered table-condensed zebra-striped tablesorter" id='search-result-details'>
    		<thead id='head-table'>
    				<tr>
                        <th><input type="checkbox" class="checkall" /></th>
                        <th>SupplierName</th>
                        <th>Name</th>
                        <th>Model</th>
                        <th>SerialNumber</th>
                        <th>ReceivedDate</th>
                        <th>StockStatus</th>
                        <th>Note</th>
                        <th>Description</th>
                        <th>Price</th>
                    </tr>
    		</thead>
    				<tbody>
    			<?php foreach($this->list as $row) :?>
    			<tr id="<?php echo $row['id'];?>" >
    			<?php /*<td><a href="<?php echo node_link('product', $row);?>"><?php echo $row['Model'];?></a></td>*/?>
    				<td> <input type="checkbox" value="<?php echo $row['_id'];?>" class="check-item" 
    				data-sn='<?php echo $row['SerialNumber'];?>'
    				/> </td>
    				<td><?php echo $row['SupplierName'];?></a></td>
    				<td><?php echo $row['name'];?></td>
    				<td><?php echo $row['Model'];?></td>
    				<td><?php echo $row['SerialNumber'];?></td>
    				<td><?php echo $row['ReceivedDate'];?></td>
    				<td><?php echo $row['StockStatus'];?></td>
    				<td><?php echo $row['Note'];?></td>
    				<td><?php echo $row['description'];?></td>
    				<td><?php echo $row['price'];?></td>				
    	           
    				<td>
    				    <a href="/product/update?id=<?php echo $row['id'];?>" class="btn btn-mini"><i class="icon-edit"></i>Edit</a>
    				    <?php if (has_perm('admin_product')):?>
    				    <a href="/product/delete?id=<?php echo $row['id'];?>" class="btn btn-mini btn-danger cl_ajax" 
    				        _cl_get_metadata="remove_my_parent:2"
    				        _cl_ajax_confirm='Are you sure you want to permanently delete this item?'
    				        >
                           <i class="icon-remove"></i>Delete
    				       </a>
    				    <?php endif;?>
    			   </td>
    			</tr>
    			<?php endforeach; ?>	
    		</tbody>
            		
    	</table>
    	
    	<?php else:?>
        	<h3 style="text-align: center; color: red;">No item found</h3>
        <?php endif;?>
    </div>
    </div>