<?php $categories = $this->categories;?>
<?php 
	$products = $this->products;
	$key = $this->key;
	$dealestProducts = $this->dealestProducts;
	$newProducts = $this->newProducts;
	$bestSellingProducts = $this->bestSellingProducts;
?>
<section class="main row">
	<div class="twelve columns">
		<section id="main" class="module">
			<div id="content" class="module-body">
				<div id="deal_content" class="two-col-nav">
					<div id="js-page-header" class="page_header">
						<div>
							<h2 class="browse-title-heading">
                				<span data-bhc="query:sho" >
                				Kết quả từ khóa :: "<?php echo $key;?>"</span>
						    </h2>
						</div>
						<div class="dotted-line"></div>
					</div>
					
					<div id="refinement-bar" class="tow columns">
						<div id="refinement-box refinement-links-wrapper" class="refinement-links-wrapper">
							<div data-id="travel" class="refinement flat-refinements top-category-links">
							    <h4> Chuyên mục</h4>
							    <ul id="travel-list">
							        <?php if(isset($categories)):?>
							          	<?php foreach ($categories as $ca):?>
									      <li>
									      	<a href="<?php echo category_link($ca)?>">
									      		<?php echo $ca['name']?>
									      <?php $count_child = (isset($ca['child_category']) && count($ca['child_category']) > 0) ? count($ca['child_category']) : 0;?>
									      		<span class="counter">(<?php echo $count_child;?>)</span></a></li>
							          	<?php endforeach;?>
							          <?php endif;?>
							  </ul>
							  </div>
						</div>
					</div>
					
					<div id="deal-space" class="ten columns deal-space deal-tile-grid-view ">
					  <?php if(count($products) > 0):?>
							<div class="content">
							   <?php $first = Dao_Node_Product::getInstance()->getStandedProduct($products[0]);?>
							   <?php if(isset($first)):?>
							   		<?php $this->row = $first;?>
							   		<?php echo $this->render('index/product_detail.phtml');?>
								<?php endif;?>
								
								<div style='clear: both;'></div>
								<?php if(count($products) > 1):?>
								  <?php 
							  		$this->product_list = $products;
							  		$this->product_list_name = 'Những kết quả khác của "' . $key .'"';
							  		$this->product_list_link = "/product/dealest";
							  		echo $this->render('widget/product_list.phtml');
								  ?>
							  	<?php endif;?>
						  <?php else:?>
							<div id="deal_space_message_content" style="display: block;">
							  	<div class="notification info">
							  	  <div class="no-deals-message">
										 Hiện tại không có sản phẩm nào tương đồng với kết quả "<?php echo $key;?>"
								  	  	</div>
							  	    <div class="no-deals-suggestion">
							  	    	Bạn có thể lựa chọn các sản phẩm ưu đãi khác của <?php echo SITE_NAME;?>.</div>
								</div>
							</div>
							
							<?php if(count($dealestProducts) > 0):?>
						        <?php 
							  		$this->product_list = $dealestProducts;
							  		$this->product_list_name = "Sản phẩm giảm giá nhiều";
							  		$this->product_list_link = "/product/dealest";
							  		echo $this->render('widget/product_list.phtml');
							  	?>
							  <?php endif;?>
									  
									  
							 <?php if(count($newProducts) > 0):?>
							 <?php 
							  		$this->product_list = $newProducts;
							  		$this->product_list_name = "Sản phẩm mới nhất";
							  		$this->product_list_link = "/product/newest";
							  		echo $this->render('widget/product_list.phtml');
							  	?>
						  	 <?php endif;?>
						  	 
						  	 <?php if(count($bestSellingProducts) > 0):?>
							 <?php 
							  		$this->product_list = $bestSellingProducts;
							  		$this->product_list_name = " Sản phẩm bán chạy nhất";
							  		$this->product_list_link = "/product/newest";
							  		echo $this->render('widget/product_list.phtml');
							  	?>
						  	 <?php endif;?>
						  <?php endif;?>
							</div>
					</div>
				</div>
			</div>
		</section>
	</div>
</section>