<div class='row'>

<?php if (isset($this->row)):?>
<?php 
    $row = $this->row;
    $row = Dao_Node_Product::getInstance()->getStandedProduct($row);
    $lu = Zend_Registry::get('user');
    $dealestProducts = $this->dealestProducts;
    $newProducts = $this->newProducts;
    $bestSellingProducts = $this->bestSellingProducts;
    $related = $this->related;
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>
<div class="col-md-12">
<section class="main">
  <div class="row">
    <div class="columns twelve">
      <section class="module deal">
      	<?php echo $this->render('index/product_detail.phtml');?>
      </section>
      
	    <?php /*San pham tai cac hang khac*/?>
	    <?php if(isset($related) && count($related) > 0):?>
	    <section class='module deal'>
	    	<div class='row'>
	    		<div class='columns twelve'>
	    			<table>
	    				<thead>
	    					<tr>
	    						<th style='width: 10%; font-weight: bold;'>Hình ảnh</th>
	    						<th style='width: 55%; font-weight: bold;'>Mô tả sản phẩm</th>
	    						<th style='width: 20%; font-weight: bold;'>Nơi bán</th>
	    						<th style='font-weight: bold;'>Giá bán</th>
	    					</tr>
	    				</thead>
	    				
	    				<tbody>
				     		<?php foreach ($related as $r):?>
								<tr>
									<td class='bottom-td-related'><img src='<?php echo STATIC_GT . $r['images']?>' 
										width='85px'/></td>
									<td class='bottom-td-related'>
										<span style='font-weight: bold; text-align: center;'>
										<?php echo $r['name']?></span><br>
										<?php echo $r['description'];?>
										</td>
									<td class='bottom-td-related'><span style='font-weight: bold; text-align: center;'>
										<?php echo $r['brand'];?></span><br>
										<img src='<?php echo STATIC_GT . $r['avatar_brand'];?>'/>
										</td>
									<td class='bottom-td-related'>
										<span style='font-weight: bold; text-align: center;'>
										<?php echo show_money($r['origin_price']);?></span><br>
										<a href="<?php echo $r['link'];?>" target='_blank' 
											class="btn-buy-big" style='font-size: 10px;'>
		          							Đến nơi bán
		        							</a>
										</td>
								</tr>				
				     		<?php endforeach;?>
	    				</tbody>
	    			</table>
	    		</div>
	    	</div>
	    </section>
		<?php endif;?>

        <section class="write-up module" >
          <div class="module-body dotted-border">
              <div class="row hide-diy-gift-card-msg">
        		<article class="seven columns pitch">
			         <?php echo $row['description'];?>				
                </article>
      
	        	<article class="four columns">
	                <div data-bhw="DealFineDetails" class="" >
	                	<?php echo $row['description'];?>
					  </div>
	        	</article>
	     	 </div>
          </div>
        </section>


        <?php if(count($dealestProducts) > 0):?>
        <?php 
	  		$this->product_list = $dealestProducts;
	  		$this->product_list_name = "Sản phẩm giảm giá nhiều";
	  		$this->product_list_link = "/product/dealest";
	  		echo $this->render('widget/product_list.phtml');
	  	?>
	  <?php endif;?>
			  
			  
	 <?php if(count($newProducts) > 0):?>
	 <?php 
	  		$this->product_list = $newProducts;
	  		$this->product_list_name = "Sản phẩm mới nhất";
	  		$this->product_list_link = "/product/newest";
	  		echo $this->render('widget/product_list.phtml');
	  	?>
  	 <?php endif;?>
  	 
  	 <?php if(count($bestSellingProducts) > 0):?>
	 <?php 
	  		$this->product_list = $bestSellingProducts;
	  		$this->product_list_name = " Sản phẩm bán chạy nhất";
	  		$this->product_list_link = "/product/newest";
	  		echo $this->render('widget/product_list.phtml');
	  	?>
  	 <?php endif;?>
    </div>
  </div>
</section>
</div>
    <?php endif;?>
</div>

<style>
.bottom-td-related{
	border-bottom: 1px solid #D5D5D5;
	padding: 10px;
}			          				          
</style>