<div class='row'>

<?php if (isset($this->row)):?>
<?php 
    $row = $this->row;
    $lu = Zend_Registry::get('user');
?>
<script type="text/javascript">
CL.NID = "<?php echo $row['id']; ?>";
</script>
    <div class="col-md-12">
        <div class="">
            <?php echo $row['name'];?>
        </div>
        <div class="">
            <?php echo $row['price'];?>
        </div>
        <div class="">
            <?php echo $row['images'];?>
        </div>
        <div class="">
            <?php echo $row['description'];?>
        </div>
    </div>
    <?php endif;?>
</div>