<div>
Các hình thức thanh toán

Các hình thức thanh toán cụ thể như sau:
1. Thanh toán tiền mặt cho người giao hàng
Nếu địa điểm giao hàng và thanh toán đều là một và thuộc nội thành Hà Nội thì Giasomotsẽ thu tiền khi giao hàng mà không cần đặt cọc.

2. Chuyển khoản qua ngân hàng
 - Nếu địa điểm giao hàng khác với địa điểm thanh toán (trong trường hợp Quý khách gửi quà, gửi hàng cho bạn bè, đối tác …) Giasomotsẽ thu tiền trước 100% giá trị hàng + phí vận chuyển theo cước phí tính trong chinh sách vận chuyển bằng phương thức chuyển khoản trước khi giao hàng.
- Quý khách thanh toán qua ngân hàng, vui lòng chuyển tiền đến tài khoản của Cty CP Giasomotđược mở tại một trong các ngân hàng dưới đây:

- Sau khi nhận được giấy báo nhận tiền từ ngân hàng, chúng tôi sẽ thực hiện đơn hàng theo yêu cầu của Quý khách.  


3. Hình thức thanh toán trực tuyến 
</div>