<div class="row">
  <section class="nine columns login-section">
    <div class="module">
      <h1 class="section-title">
        Sign In
        <span>
          or
          <a href="/signup">
            Sign Up
          </a>
        </span>
      </h1>

      <div class="module-body">
        <div class="row" id="login">
            <div data-bhw="Login" class="facebook-login five columns" data-bhw-path="Login">
              <h3>
                Sign in with your Facebook account
              </h3>
          
              <p>Connect your Facebook account to sign in to Groupon.</p>
          
              <div class="fb-login-button">
                <div class="facebook-login-button"></div>
              </div>
            </div>
          <div class="section-spacer">
            <span>or</span>
          </div>
          
          <div class="groupon-login six columns push-one">
            <h3>
              Sign in with your Groupon account
            </h3>
          
            <form class="session-form" data-bhw="LoginForm" method="post" action="/login?message=&amp;ref=%2F" data-bhw-path="LoginForm">
              <fieldset>
                <input type="hidden" value="e00ca0f0a14b11e3b45c2586f50c6d9d" name="_csrf">

                <div class="field">
                  <label class="three columns text-right">Email</label>
                  <input type="email" value="" class="nine input-small" name="email" data-bhc="text:email" data-bhc-path="LoginForm|text:email">
                </div>
          
                <div class="field">
                  <label class="three columns text-right">Password</label>
                  <input type="password" class="nine input-small" name="password" data-bhc="text:password" data-bhc-path="LoginForm|text:password">
                </div>
          
                <div class="caption offset-by-three" id="forgot-password">
                  <a href="/forgot_password" data-bhc="link:forgot password" data-bhc-path="LoginForm|link:forgot password">Forgot your password?</a>
                </div>
          
                <div class="field">
                  <p class="offset-by-three">
                    <input type="checkbox" value="1" checked="checked" name="remember_me" data-bhc="checkbox:remember me" data-bhc-path="LoginForm|checkbox:remember me"> Keep me signed in on this computer
                  </p>
                </div>
              </fieldset>
          
              <fieldset class="buttons">
                <div class="field">
                  <input type="submit" value="Sign In" class="btn btn-small signin-btn" data-bhc="button:submit" data-bhc-path="LoginForm|button:submit">
          
                  <span class="caption">
                    <a href="/signup?ref=%2F" data-bhc="link:signup" data-bhc-path="LoginForm|link:signup">Not a member yet?</a>
                  </span>
                </div>
              </fieldset>
            </form>
          </div>
          
        </div>

          <div data-bhw="BasicLogin" data-bhw-path="BasicLogin">
              <div data-bhc="user state:subscribed" data-bhc-path="BasicLogin|user state:subscribed"></div>
  </div>
      </div>
    </div>
  </section>

  <section class="three columns">
    <section data-bhw="GrouponPromise" id="promise" class="module" data-bhw-path="GrouponPromise">
      <h3 class="module-title">Our Promise To You</h3>
  
      <div class="module-body">
        <p>We're confident in the businesses we feature on Groupon and back them with the Groupon Promise.</p>
        <p>
          <a href="/groupon-promise">Learn more</a>
        </p>
      </div>
    </section>
  </section>
</div>