<?php $lu = Zend_Registry::get('user');?>
<div class="header-v2">
        <header role="banner" data-bhw="Header" class="header" data-bhw-path="Header">
          <div class="row">
            <div class="ten columns ">
              <div class="row">
                 
                  <div class="four columns user-wrapper">
                      <?php if(is_guest()):?>
                          <nav class="user-menu signed-out">
	                              <a data-bhw="SignIn" href="/user/login" class="first" data-bhw-path="Header|SignIn">Sign In</a>
	                              <a data-bhw="SignUp" href="/user/register" data-bhw-path="Header|SignUp">Sign Up</a>
                          </nav>
				      <?php else:?>
				          <nav class="user-menu signed-in">
		                      <a class="user-name icon-arrow-down-large" href="/mygroupons">
		                      	<?php echo $lu['name'];?></a>
			                      <ul class="my-stuff">
			                      	<li><a href="/" 
			                        	id="home-page">Trang chủ</a></li>
			                      	<li><a href="/user/<?php echo $lu['id'];?>" 
			                        	id="user-groupons">Trang cá nhân</a></li>
			                        <li><a href="/user/update?id=<?php echo $lu['id']?>&_cl_step=account" 
			                        	id="user-account">Sửa thông tin</a></li>
			                        <li><a href="/user/update?id=<?php echo $lu['id']?>&_cl_step=change_pass" 
			                        	id="change_pass">Đổi mật khẩu</a></li>
		              			    <li><a id="sign-out" class="sign-out" 
		              			    	href="/user/logout">Đăng suất</a></li>
			                      </ul>
                    		</nav>	
                       <?php endif;?>
		        </div>
              </div>
            </div>
          </div>
        </header>        
      </div>