<?php 
    $lu =  Zend_Registry::get('user');
    $page = 'home';
    if (isset($_REQUEST['page']))
        $page = $_REQUEST['page'];
    if (Zend_Registry::isRegistered('page'))
        $page = Zend_Registry::get('page');

?>
<!DOCTYPE html>
<html>
	<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Bootstrap::$pageTitle;?> - demo.com</title>
    <meta name="description" content="<?php echo Bootstrap::$pageDesc;?>" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="">
    
<?php //if (APPLICATION_ENV == 'development') :?>
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/ui-lightness/jquery-ui-1.8.16.custom.css" rel="stylesheet" >
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/reset.css" media="screen" rel="stylesheet" type="text/css" >
    
	<link href="<?php echo SAND_ASSETS_CDN;?>bootstrap-3.0.0/dist/css/bootstrap.min.css" rel="stylesheet">
    
    <link href="<?php echo SAND_ASSETS_CDN;?>/css/common.css" media="screen" rel="stylesheet" type="text/css" >
	<link href="<?php echo ASSETS_CDN;?>/css/styles.css" media="screen" rel="stylesheet" type="text/css" >
    <link href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/resources/css/jquery.toastmessage.css" rel="stylesheet" type="text/css"/>	
<?php
/* 
//else 
//<link href="<?php echo ASSETS_CDN . "css/_v" . JSVERSION . ".css"?>" media="screen" rel="stylesheet" type="text/css" >
// endif;
 * 
 */
?>

<style>
div.navbar ul.breadcrumb > li
{
	min-height:30px;
	padding-top:10px;
}
</style>
<?php 
$format = "DD/MM/YYYY";
?>

<script type='text/javascript'>
<?php echo $this->render('widget/php-to-js.phtml');?>
CL.DATE_FORMAT = "<?php echo substr(strtolower($format), 0, -2);?>";
</script>
	
</head>
<body> 
<?php if ($lu['id'] != GUEST_ID && !Zend_Registry::isRegistered('guest_mode')) :?>
<div class="navbar navbar-default navbar-fixed-top">
            <ul class="breadcrumb" >
            <?php if (has_perm('sudo')) :?>
 			<li class="">
				<a href="/site/admin"><i class='icon-legal' style="color:red"></i>Admin</a>
          	</li>
            <?php endif;?>
 			<li class="">
				<a href="/"><i class='icon-home' style="color:black"></i> Home</a>
          	</li>
            

 			<li class="dropdown">
 				<i class='icon-exclamation-sign' style="color:red"></i>
 				<a href="javascript:;" type="request" data-toggle="dropdown" class="dropdown-toggle notif-dropdown">
 					Requests <?php $count = get_notification_count($lu, 'request');?>
 					<?php if ($count >0):?><span class="badge badge-important request-notif-count"><?php echo $count;?></span><?php endif;?><b class="caret"></b>
 				</a>
 				<ul class="dropdown-menu"></ul>
            </li>

 			<li class="dropdown">
 				<i class='icon-info-sign'></i>
 				<a href="javascript:;" type="notice" data-toggle="dropdown" class="dropdown-toggle notif-dropdown">
 					Notifications <?php $count = get_notification_count($lu, 'notice');?>
 					<?php if ($count >0):?><span class="badge badge-info notice-notif-count"><?php echo $count;?></span><?php endif;?><b class="caret"></b>
 				</a>
 				<ul class="dropdown-menu"></ul>
            </li>
            <li style="float:right">
            <i class='icon-off'></i> <a href="/user/logout">Log out</a>
            </li>

            <li style="float:right">
            <a href='/user/<?php echo $lu['id'];?>'><i class="icon-user"></i> <?php echo $lu['name']?></a> 
            
            </li>


    		<li class="dropdown" style="float:right">
    			<i class="icon-star" style="color:green"></i> <a href="#" class="dropdown-toggle" data-toggle="dropdown">School 
    				<b class="caret"></b>
    			</a>
        	 
            </li>
            </ul>
</div>
<?php else:?>
	<?php echo $this->render("guest_menu.phtml");?>
<?php endif;?>
<div class='container'>
    <div class='row' style='min-height:65px;'></div>
</div>

<div class='container' style='min-height:500px;' >
     <?php echo $this->layout()->content; ?>
</div>
     
<div class='container'>     
    <div class='row'>
    	<div class='col-md-12'>
            Copyright &copy; 2013 <strong>demo.com</strong> <br/>
            
                <a href="/page/contact">Contact</a> · 
                <a href="/page/about-us.html">About Us</a> · 
                <a href="/page/privacy.html">Privacy</a> · 
                <a href="/page/terms.html">Terms Of Service</a> · 
                <a href="/page/help.html" title="Help on how to use the website">Help</a> 
        </div>
    </div>
</div>


    <script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery.js"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/jquery-ui-1.8.16.custom.min.js"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/toastmessage/src/main/javascript/jquery.toastmessage.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/3rdparty/underscore-min.js" type="text/javascript"></script>
	<script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/utils.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.form.js" type="text/javascript"></script>
    
    <script type="text/javascript" src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/src/jquery.tokeninput.js"></script>
    <link rel="stylesheet" type="text/css" href="<?php echo SAND_ASSETS_CDN;?>/js/plugins/tokeninput/styles/token-input-facebook.css" />
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax_metadata_config.js" type="text/javascript"></script>
    <?php /*<script type="text/javascript" src="<?php echo SAND_ASSETS_CDN;?>/js/tinymce/tinymce_3.5.2/jscripts/tiny_mce/tiny_mce.js"></script>*/?>
    <script type="text/javascript" src="<?php echo SITE_URL;?>/tinymce/tinymce_3.5.2/jscripts/tiny_mce/tiny_mce.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/vi.js"></script>
    <script src="<?php echo ASSETS_CDN;?>/js/site.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/comment.js" type="text/javascript"></script>
    
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/cl_ajax.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/sand/site_common.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/jquery.ui.datepicker.js" type="text/javascript"></script>
    <script src="<?php echo SAND_ASSETS_CDN;?>/js/plugins/autoresize.jquery.js" type="text/javascript"></script>
    
    
    <script src="<?php echo SAND_ASSETS_CDN;?>/bootstrap/js/bootstrap.min.js"></script>    
<?php echo $this->headScript();?>
<?php print $this->inlineScript();?>
</body>
</html>

